project:
  type: website

website:
  title: "rcounting"
  sidebar:
    style: "floating"
    search: false
    contents:
    - section: Analysis
      contents:
        - index.qmd
        - separators.qmd
        - runs.qmd
        - network.qmd
        - counting_counters.qmd
        - time.qmd
        - distribution.qmd
        - dst.qmd
        - side_threads.qmd
    - examples.qmd
  page-footer:
    center:
      - text: "About"
        href: about.qmd
      - text: "Github"
        href: https://github.com/cutonbuminband/rcounting
bibliography: references.bib
format:
  html:
    anchor-sections: true
    code-tools: true
    code-fold: show
    theme:
        light: flatly
        dark: darkly
    css: styles.css
    toc: true
    reference-location: margin
    citation-location: margin
    highlight-style: pygments
execute:
  freeze: auto
