* Ideas for future posts

A loosely-organised list of things which would be interesting to look at in the future

- For one, you could try to divide counters into runners or those who count in bursts and counters who are more or less active evenly. This could be done by taking the time (i think it makes more sense than raw count difference) between their successive comments. Then you could count a mean (not arithmetic tho, perhaps something like weighted idk) and calculate the standard deviation as well

- For another, you could try taking a look which counters have filled the gaps in time when there was no one active, meaning they placed a number that it took a lot of time to reply to (meaning next comment appeared an hour later or so) as opposed to people who count at popular times and time gaps aren't that large. So, like a gap filler leaderboard based on some sort of mean

- One more. It would be interesting to see who's most and least talkative from, let's say, top50 hoc, based on the number of characters in their main thread counts. You could also try to check if we chat more or less over the years
